### ISSUE TITLE
Layout issue on Dashboard (MacOS 10.12, FF ESR & Safari)

### ISSUE THREAD

**Issue by hrmgamer** [chrisjrn/registrasion#107]
On MacOS 10.12.1 with Firefox ESR 45.6.0 and Safari 10.0.1 (12602.2.14.0.7) the Dashboard page consistently places the footer div near the top of the page.

Had a cursory look at the code, and it appears the footer is inside the wrong div when compared to other pages.

Screen shot of the problem (highlighted the text so you could see the overlapping more clearly):

<img width="1177" alt="screen shot 2017-01-18 at 16 04 00" src="https://cloud.githubusercontent.com/assets/2586425/22051564/4244d8ba-dd98-11e6-9391-47dab8a04330.png">

**Comment by chrisjrn** [comment]
This presumably belongs at lca2017/website. Closing.
