### ISSUE TITLE
Invoice line items render in reverse order on Heroku w/ Postgres.

### ISSUE THREAD

**Issue by chrisjrn** [chrisjrn/registrasion#21]

**Comment by mjec** [comment]
Presumably the fix for this is to add [explicit ordering](https://docs.djangoproject.com/en/1.9/ref/models/options/#ordering) to `models.LineItem`?

``` Python
  class LineItem(models.Model):
    # ...
    class Meta:
      ordering = ['id']
```

**Comment by chrisjrn** [comment]
Yup.

There's a bunch of other models that could use this fix too, but LineItem
is the relevant one here.

**Comment by chrisjrn** [comment]
Fix in progress
